GET http://localhost:4000/course


###

POST http://localhost:4000/course
Content-Type: application/json

{
    "name": "test",
    "description": "this is the description"
}

###

GET http://localhost:4000/course/606d661b384bcd23d00c3a6d



###
DELETE http://localhost:4000/course/606d661b384bcd23d00c3a6d


###
POST  http://localhost:4000/recipe/create
Content-Type: application/json

{
    "name": "Calvin Special",
    "steps": [{"actionId": "234", "depends": [1,2,3]}],
    "ingredients": ["B1213"],
    "category": "Milk Tea",
    "archive": false
}

###
GET http://localhost:4000/recipe

###
PUT http://localhost:4000/recipe/607182cb7cac42f7d50da7ee
Content-Type: application/json

{
    "name": "MotherFUcker ",
    "steps": [{"actionId": "234", "depends": [1,2,3]}],
    "ingredients": ["B1213"],
    "category": "Milk Tea",
    "archive": false
}

###
DELETE http://localhost:4000/recipe/607196ca23d5300976c82c52