GET http://localhost:4000/course


###

POST http://localhost:4000/course
Content-Type: application/json

{
    "name": "test",
    "description": "this is the description"
}

###

POST http://localhost:4000/course/606d6620384bcd23d00c3a6f
Content-Type: application/json

{
    "name": "test",
    "description": "this is the description"
}
